"""Generate the TypeScript Trilogy syntax reference used by the frontend."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import trilogy
from trilogy.ai.constants import AGGREGATE_FUNCTIONS, FUNCTIONS, RULE_PROMPT
from trilogy.ai.prompts import get_trilogy_syntax_reference
from trilogy.authoring import DataType

DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[2]
    / "lib"
    / "llm"
    / "data"
    / "trilogySyntax.generated.ts"
)


def serialize(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def render_guidance() -> str:
    source_version = trilogy.__version__
    return f"""// Generated by pnpm sync:trilogy-ai from pytrilogy {source_version}.
// Do not edit this file directly.

export const pytrilogySyntaxVersion = {serialize(source_version)}
export const trilogySyntaxReference = {serialize(get_trilogy_syntax_reference().strip())}
export const rulesInput = {serialize(RULE_PROMPT.strip())}
export const aggFunctions = {serialize([line for line in AGGREGATE_FUNCTIONS.splitlines() if line])}
export const functions = {serialize([line for line in FUNCTIONS.splitlines() if line])}
export const datatypes = {serialize([value.value for value in DataType])}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    output = args.output.resolve()
    generated = render_guidance()
    current = output.read_text(encoding="utf-8") if output.exists() else ""

    if args.check:
        if current != generated:
            print(
                "Generated Trilogy AI guidance is stale. "
                "Run `pnpm sync:trilogy-ai` and commit the result."
            )
            return 1
        print(f"Trilogy AI guidance matches pytrilogy {trilogy.__version__}.")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Generated {output} from pytrilogy {trilogy.__version__}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
